### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by TimMoore**
Replace with a link to https://www.lightbend.com/conduct

### CODE REVIEW

**Comment by ennru** [comment]
Some repositories contain the file explicitly, as well.
Such as 
- [ ] https://github.com/akka/akka/blob/master/CODE_OF_CONDUCT.md
- [ ] https://github.com/akka/akka-http/blob/master/CODE_OF_CONDUCT.md
- [ ] https://github.com/akka/alpakka/blob/master/CODE_OF_CONDUCT.md
- [ ] https://github.com/akka/alpakka-kafka/blob/master/CODE_OF_CONDUCT.md

Some places in the docs might refer to those files.

**Review by ennru — APPROVED** [review]
LGTM.

**Review by raboof — APPROVED** [review]
Nice to be able to get behind a widely-used and understood CoC rather than have our own wording, though the gist is the same :+1:

**Comment by TimMoore** [comment]
@ennru I'll clean up the others in separate pull requests once this is merged. I don't have permissions to self-merge in Akka so I'll need one of you to do it. 😄

**Pull request merged**
